SET SERVEROUTPUT ON;

CREATE SEQUENCE seq_paciente START WITH 1;
CREATE SEQUENCE seq_medico START WITH 1;
CREATE SEQUENCE seq_cita START WITH 1;
CREATE SEQUENCE seq_factura START WITH 1;
CREATE SEQUENCE seq_historial START WITH 1;

CREATE TABLE PACIENTE(
    id_paciente NUMBER PRIMARY KEY,
    nombre VARCHAR2(50),
    apellido VARCHAR2(50),
    telefono VARCHAR2(20),
    correo VARCHAR2(100),
    fecha_registro DATE
);
CREATE TABLE MEDICO(
    id_medico NUMBER PRIMARY KEY,
    nombre VARCHAR2(50),
    especialidad VARCHAR2(50),
    telefono VARCHAR2(20),
    salario NUMBER
);

CREATE TABLE CITA(
    id_cita NUMBER PRIMARY KEY,
    id_paciente NUMBER,
    id_medico NUMBER,
    fecha_cita DATE,
    estado VARCHAR2(20)
);
CREATE TABLE FACTURACION(
    id_factura NUMBER PRIMARY KEY,
    id_paciente NUMBER,
    monto_total NUMBER,
    estado_pago VARCHAR2(20)
);
CREATE TABLE HISTORIAL_MEDICO(
    id_historial NUMBER PRIMARY KEY,
    id_paciente NUMBER,
    fecha DATE,
    diagnostico VARCHAR2(200),
    tratamiento VARCHAR2(200),
    observaciones VARCHAR2(200)
);
CREATE OR REPLACE TRIGGER trg_paciente
BEFORE INSERT ON PACIENTE
FOR EACH ROW
BEGIN
    :NEW.id_paciente := seq_paciente.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER trg_medico
BEFORE INSERT ON MEDICO
FOR EACH ROW
BEGIN
    :NEW.id_medico := seq_medico.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER trg_cita
BEFORE INSERT ON CITA
FOR EACH ROW
BEGIN
    :NEW.id_cita := seq_cita.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER trg_factura
BEFORE INSERT ON FACTURACION
FOR EACH ROW
BEGIN
    :NEW.id_factura := seq_factura.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER trg_historial
BEFORE INSERT ON HISTORIAL_MEDICO
FOR EACH ROW
BEGIN
    :NEW.id_historial := seq_historial.NEXTVAL;
END;
/
CREATE OR REPLACE FUNCTION fn_total_pacientes RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM PACIENTE; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_total_medicos RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM MEDICO; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_total_citas RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM CITA; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_total_facturas RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM FACTURACION; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_salario_total RETURN NUMBER IS v NUMBER;
BEGIN SELECT SUM(salario) INTO v FROM MEDICO; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_promedio_salario RETURN NUMBER IS v NUMBER;
BEGIN SELECT AVG(salario) INTO v FROM MEDICO; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_citas_hoy RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM CITA WHERE TRUNC(fecha_cita)=TRUNC(SYSDATE); RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_facturas_pendientes RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM FACTURACION WHERE estado_pago='PENDIENTE'; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_facturas_pagadas RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM FACTURACION WHERE estado_pago='PAGADO'; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_max_factura RETURN NUMBER IS v NUMBER;
BEGIN SELECT MAX(monto_total) INTO v FROM FACTURACION; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_min_factura RETURN NUMBER IS v NUMBER;
BEGIN SELECT MIN(monto_total) INTO v FROM FACTURACION; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_total_historial RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM HISTORIAL_MEDICO; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_citas_activas RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM CITA WHERE estado='ACTIVA'; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_citas_canceladas RETURN NUMBER IS v NUMBER;
BEGIN SELECT COUNT(*) INTO v FROM CITA WHERE estado='CANCELADA'; RETURN v; END;
/
CREATE OR REPLACE FUNCTION fn_total_ingresos RETURN NUMBER IS v NUMBER;
BEGIN SELECT SUM(monto_total) INTO v FROM FACTURACION; RETURN v; END;
/
CREATE OR REPLACE VIEW vw_pacientes AS SELECT * FROM PACIENTE;
CREATE OR REPLACE VIEW vw_medicos AS SELECT * FROM MEDICO;
CREATE OR REPLACE VIEW vw_citas AS SELECT * FROM CITA;
CREATE OR REPLACE VIEW vw_facturacion AS SELECT * FROM FACTURACION;
CREATE OR REPLACE VIEW vw_historial AS SELECT * FROM HISTORIAL_MEDICO;
CREATE OR REPLACE VIEW vw_ingresos AS
SELECT SUM(monto_total) total FROM FACTURACION;
CREATE OR REPLACE VIEW vw_citas_activas AS
SELECT * FROM CITA WHERE estado='ACTIVA';
CREATE OR REPLACE VIEW vw_citas_canceladas AS
SELECT * FROM CITA WHERE estado='CANCELADA';
CREATE OR REPLACE VIEW vw_medicos_especialidad AS
SELECT nombre, especialidad FROM MEDICO;
CREATE OR REPLACE VIEW vw_pacientes_recientes AS
SELECT * FROM PACIENTE WHERE fecha_registro > SYSDATE-30;

CREATE OR REPLACE PROCEDURE sp_insert_paciente(n VARCHAR2,a VARCHAR2,t VARCHAR2,c VARCHAR2)
IS BEGIN INSERT INTO PACIENTE VALUES(NULL,n,a,t,c,SYSDATE); END;
/
CREATE OR REPLACE PROCEDURE sp_update_paciente(id NUMBER,n VARCHAR2)
IS BEGIN UPDATE PACIENTE SET nombre=n WHERE id_paciente=id; END;
/
CREATE OR REPLACE PROCEDURE sp_delete_paciente(id NUMBER)
IS BEGIN DELETE FROM PACIENTE WHERE id_paciente=id; END;
/
CREATE OR REPLACE PROCEDURE sp_insert_medico(n VARCHAR2,e VARCHAR2,t VARCHAR2,s NUMBER)
IS BEGIN INSERT INTO MEDICO VALUES(NULL,n,e,t,s); END;
/
CREATE OR REPLACE PROCEDURE sp_update_medico(id NUMBER,s NUMBER)
IS BEGIN UPDATE MEDICO SET salario=s WHERE id_medico=id; END;
/
CREATE OR REPLACE PROCEDURE sp_delete_medico(id NUMBER)
IS BEGIN DELETE FROM MEDICO WHERE id_medico=id; END;
/
CREATE OR REPLACE PROCEDURE sp_insert_cita(p NUMBER,m NUMBER,f DATE,e VARCHAR2)
IS BEGIN INSERT INTO CITA VALUES(NULL,p,m,f,e); END;
/
CREATE OR REPLACE PROCEDURE sp_delete_cita(p NUMBER)
IS BEGIN DELETE FROM CITA WHERE id_cita=p; END;
/
CREATE OR REPLACE PROCEDURE sp_update_cita_estado(p NUMBER,e VARCHAR2)
IS BEGIN UPDATE CITA SET estado=e WHERE id_cita=p; END;
/
CREATE OR REPLACE PROCEDURE sp_insert_factura(p NUMBER,m NUMBER,e VARCHAR2)
IS BEGIN INSERT INTO FACTURACION VALUES(NULL,p,m,e); END;
/
CREATE OR REPLACE PROCEDURE sp_update_factura(p NUMBER,m NUMBER)
IS BEGIN UPDATE FACTURACION SET monto_total=m WHERE id_factura=p; END;
/
CREATE OR REPLACE PROCEDURE sp_delete_factura(p NUMBER)
IS BEGIN DELETE FROM FACTURACION WHERE id_factura=p; END;
/
CREATE OR REPLACE PROCEDURE sp_insert_historial(p NUMBER,d VARCHAR2,t VARCHAR2,o VARCHAR2)
IS BEGIN INSERT INTO HISTORIAL_MEDICO VALUES(NULL,p,SYSDATE,d,t,o); END;
/
CREATE OR REPLACE PROCEDURE sp_aumentar_salarios(p NUMBER)
IS BEGIN UPDATE MEDICO SET salario=salario+p; END;
/
CREATE OR REPLACE PROCEDURE sp_reset_estado_citas
IS BEGIN UPDATE CITA SET estado='ACTIVA'; END;
/

CREATE OR REPLACE PROCEDURE sp_proc1 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc2 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc3 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc4 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc5 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc6 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc7 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc8 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc9 IS BEGIN NULL; END;
/
CREATE OR REPLACE PROCEDURE sp_proc10 IS BEGIN NULL; END;
/

CREATE OR REPLACE PROCEDURE sp_cursor1 IS CURSOR c IS SELECT nombre FROM PACIENTE;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.nombre); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor2 IS CURSOR c IS SELECT nombre FROM MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.nombre); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor3 IS CURSOR c IS SELECT apellido FROM PACIENTE;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.apellido); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor4 IS CURSOR c IS SELECT especialidad FROM MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.especialidad); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor5 IS CURSOR c IS SELECT monto_total FROM FACTURACION;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.monto_total); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor6 IS CURSOR c IS SELECT estado FROM CITA;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.estado); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor7 IS CURSOR c IS SELECT correo FROM PACIENTE;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.correo); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor8 IS CURSOR c IS SELECT telefono FROM MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.telefono); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor9 IS CURSOR c IS SELECT fecha_cita FROM CITA;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.fecha_cita); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor10 IS CURSOR c IS SELECT estado_pago FROM FACTURACION;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.estado_pago); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor11 IS CURSOR c IS SELECT diagnostico FROM HISTORIAL_MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.diagnostico); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor12 IS CURSOR c IS SELECT tratamiento FROM HISTORIAL_MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.tratamiento); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor13 IS CURSOR c IS SELECT observaciones FROM HISTORIAL_MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.observaciones); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor14 IS CURSOR c IS SELECT salario FROM MEDICO;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.salario); END LOOP; END;
/
CREATE OR REPLACE PROCEDURE sp_cursor15 IS CURSOR c IS SELECT fecha_registro FROM PACIENTE;
BEGIN FOR r IN c LOOP DBMS_OUTPUT.PUT_LINE(r.fecha_registro); END LOOP; END;
/

CREATE OR REPLACE PACKAGE pkg1 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg1 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg1'); END; END;
/
CREATE OR REPLACE PACKAGE pkg2 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg2 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg2'); END; END;
/
CREATE OR REPLACE PACKAGE pkg3 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg3 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg3'); END; END;
/
CREATE OR REPLACE PACKAGE pkg4 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg4 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg4'); END; END;
/
CREATE OR REPLACE PACKAGE pkg5 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg5 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg5'); END; END;
/
CREATE OR REPLACE PACKAGE pkg6 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg6 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg6'); END; END;
/
CREATE OR REPLACE PACKAGE pkg7 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg7 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg7'); END; END;
/
CREATE OR REPLACE PACKAGE pkg8 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg8 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg8'); END; END;
/
CREATE OR REPLACE PACKAGE pkg9 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg9 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg9'); END; END;
/
CREATE OR REPLACE PACKAGE pkg10 AS PROCEDURE p; END;
/
CREATE OR REPLACE PACKAGE BODY pkg10 AS PROCEDURE p IS BEGIN DBMS_OUTPUT.PUT_LINE('pkg10'); END; END;
/